#ifndef TIPPSPIEL_ENUMS_H
#define TIPPSPIEL_ENUMS_H

#include <vector>
#include <string>

enum {
    ESTATUS_UPCOMING,
    ESTATUS_RUNNING,
    ESTATUS_PENDING,
    ESTATUS_ENDED
};

enum {
    GSTATUS_UPCOMING,
    GSTATUS_RUNNING,
    GSTATUS_PENDING,
    GSTATUS_ENDED
};

enum {
    GAMEPHASE_NORMAL,
    GAMEPHASE_PENALTY
};

enum {
    RESULT_SUCCESS,
    RESULT_USER_ERROR,
    RESULT_CLIENT_ERROR,
    RESULT_SERVER_ERROR
};

enum ErrCode {
    ERROR_NONE = 0,
    ERROR_NOT_LOGGEDIN = 1,
    ERROR_EMAIL_TAKEN = 2, // {email}
    ERROR_USERNAME_TAKEN = 3, // {name}
    ERROR_LOGIN_DENIED = 4, 
    ERROR_INVALID_NAME = 5, // {name}
    ERROR_GAMETIPPS_LOCKED = 6
};

#endif